; New Relic Python agent config for the Robot Shop AI Assistant.
; License key and app name come from env (NEW_RELIC_LICENSE_KEY,
; NEW_RELIC_APP_NAME); ai_monitoring is the switch that lights up the
; AI Monitoring UI from the auto-instrumented anthropic SDK calls.
[newrelic]
app_name = robot-shop-ai-assistant
monitor_mode = true
log_level = info
distributed_tracing.enabled = true
ai_monitoring.enabled = true
ai_monitoring.record_content.enabled = true
transaction_tracer.enabled = true
application_logging.enabled = true
application_logging.forwarding.enabled = true

[newrelic:production]
monitor_mode = true
