#!/usr/bin/env bash
# Generates a gitignored .env from the macOS Keychain + known constants.
# Usage:  bash scripts/load-env.sh        # writes ./.env
#         source scripts/load-env.sh      # also exports into current shell
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
ENV_FILE="$ROOT/.env"

kc() { security find-generic-password -s "$1" -w 2>/dev/null; }

NEW_RELIC_USER_KEY="$(kc newrelic_user_api_key)"
NEW_RELIC_INGEST_KEY="$(kc newrelic_ingest_license_key)"
# Optional — only present once added in Phase 5
ANTHROPIC_API_KEY="$(kc anthropic_api_key || true)"

cat > "$ENV_FILE" <<EOF
# AUTO-GENERATED by scripts/load-env.sh from macOS Keychain. Do not commit.
NEW_RELIC_USER_KEY=$NEW_RELIC_USER_KEY
NEW_RELIC_INGEST_KEY=$NEW_RELIC_INGEST_KEY
NEW_RELIC_ACCOUNT_ID=8059020
NEW_RELIC_OTLP_ENDPOINT=https://otlp.nr-data.net
NEW_RELIC_API_ENDPOINT=https://api.newrelic.com/graphql
CLUSTER=robot-shop-eks
AWS_REGION=ap-south-1
ECR_REGISTRY=926634327293.dkr.ecr.ap-south-1.amazonaws.com
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
ANTHROPIC_MODEL=claude-haiku-4-5
EOF
chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE (mode 600)."

# If sourced, export into the current shell.
if [[ "${BASH_SOURCE[0]:-}" != "${0:-}" ]]; then
  set -a; # shellcheck disable=SC1090
  source "$ENV_FILE"; set +a
  echo "Exported env into current shell (account $NEW_RELIC_ACCOUNT_ID)."
fi
